_target_: src.models.dacs_module.DACSLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.004
  eps: 1e-8

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10


